language: node_js
node_js:
  - "node"

branches:
  only:
    - master
    - /^greenkeeper/.*$/

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli@latest

script:
  - ng build
  - npm test
  - ng e2e