language: node_js
node_js:
  - "node"

branches:
  only:
    - master
    - /^greenkeeper/.*$/

install:
  - npm install -g @angular/cli@latest
  - npm install -g karma
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ng build
  - npm run test-cover

after_success:
 - npm run coveralls

notifications:
email: false