language: node_js
node_js:
  - "node"

branches:
  only:
    - master
    - /^greenkeeper/.*$/

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli@latest

script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN